@startuml

title __MENUCONFIGURACION's Class Diagram__\n

  namespace capaInterfaz {
    namespace menuConfiguracion {
      class capaInterfaz.menuConfiguracion.JDialogMenuConfiguracion {
          {static} + Password : String
          {static} + URL : String
          {static} + User : String
          {static} + botonCammbioBaseDatosPulsado : boolean
          {static} + color : Color
          - botonCambioConvocatoriaPulsado : boolean
          - botonCambioCursoPulsado : boolean
          - botonDeshacerUltimaDecisionPulsado : boolean
          - jButtonBackUp : JButton
          - jButtonCambiarConvocatoria : JButton
          - jButtonCambiarCurso : JButton
          - jButtonCancelar : JButton
          - jButtonOK : JButton
          - jButtonSelectBBDD : JButton
          - jPanel1 : JPanel
          - jPanelConfiguracion : JPanel
          - jTabbedPane1 : JTabbedPane
          + JDialogMenuConfiguracion()
          {static} + main()
          - initComponents()
          - jButtonBackUpActionPerformed()
          - jButtonCambiarConvocatoriaActionPerformed()
          - jButtonCambiarCursoActionPerformed()
          - jButtonCancelarActionPerformed()
          - jButtonOKActionPerformed()
          - jButtonSelectBBDDActionPerformed()
      }
    }
  }
  

  namespace capaInterfaz {
    namespace menuConfiguracion {
      class capaInterfaz.menuConfiguracion.JDialogMenuSeleccionarBDD {
          - jButtonBack : JButton
          - jButtonOK : JButton
          - jButtonTestConnection : JButton
          - jLabelPassword : JLabel
          - jLabelTestConnection : JLabel
          - jLabelURL : JLabel
          - jLabelUser : JLabel
          - jTextFieldPassword : JTextField
          - jTextFieldURL : JTextField
          - jTextFieldUser : JTextField
          + JDialogMenuSeleccionarBDD()
          - initComponents()
          - jButtonBackActionPerformed()
          - jButtonOKActionPerformed()
          - jButtonTestConnectionActionPerformed()
          - jTextFieldPasswordActionPerformed()
      }
    }
  }
  

  namespace capaInterfaz {
    namespace menuConfiguracion {
      class capaInterfaz.menuConfiguracion.JDialogMenuSeleccionarBDDPrimeraVez {
          - jButtonBack : JButton
          - jButtonOK : JButton
          - jButtonTestConnection : JButton
          - jLabelExplication : JLabel
          - jLabelPassword : JLabel
          - jLabelTestConnection : JLabel
          - jLabelURL : JLabel
          - jLabelUser : JLabel
          - jTextFieldPassword : JTextField
          - jTextFieldURL : JTextField
          - jTextFieldUser : JTextField
          + JDialogMenuSeleccionarBDDPrimeraVez()
          {static} + main()
          - initComponents()
          - jButtonBackActionPerformed()
          - jButtonOKActionPerformed()
          - jButtonTestConnectionActionPerformed()
          - jTextFieldPasswordActionPerformed()
      }
    }
  }
  

  capaInterfaz.menuConfiguracion.JDialogMenuConfiguracion -up-|> javax.swing.JDialog
  capaInterfaz.menuConfiguracion.JDialogMenuSeleccionarBDD -up-|> javax.swing.JDialog
  capaInterfaz.menuConfiguracion.JDialogMenuSeleccionarBDDPrimeraVez -up-|> javax.swing.JDialog


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
