@startuml

title __MENUHISTORICOALUMNOS's Class Diagram__\n

  namespace capaInterfaz {
    namespace MenuHistoricoAlumnos {
      class capaInterfaz.MenuHistoricoAlumnos.PanelMenuConsultarHistoricoAlumnos {
          {static} - LISTADO_CONSULTAR_HISTORICO_ALUMNOS : int
          {static} - MENU_HISTORICO_ALUMNOS : int
          {static} - MENU_PRINCIPAL : int
          - campo_convocatoria : JTextField
          - campo_curso : JTextField
          - campo_dni : JTextField
          + PanelMenuConsultarHistoricoAlumnos()
          + actionPerformed()
          - cargarElementos()
          - noEstaVacio()
      }
    }
  }
  

  namespace capaInterfaz {
    namespace MenuHistoricoAlumnos {
      class capaInterfaz.MenuHistoricoAlumnos.PanelMenuHistoricoAlumnos {
          {static} - MENU_CONSULTAR_HISTORICO_ALUMNOS : int
          {static} - MENU_PRINCIPAL : int
          + PanelMenuHistoricoAlumnos()
          + actionPerformed()
          - cargarElementos()
      }
    }
  }
  

  namespace capaInterfaz {
    namespace MenuHistoricoAlumnos {
      class capaInterfaz.MenuHistoricoAlumnos.PanelResultadoConsultarHistoricoAlumnos {
          {static} - GENERAR_TXT : int
          - INCREMENTOX : int
          - INCREMENTOY : int
          {static} - MENU_CONSULTAR_HISTORICO : int
          {static} - MENU_PRINCIPAL : int
          - arrayAlumno : ArrayList<JTextField>
          - arrayConvocatoria : ArrayList<JTextField>
          - arrayCurso : ArrayList<JTextField>
          - arrayDniAlumno : ArrayList<JTextField>
          - arrayNMatAlumno : ArrayList<JTextField>
          - arrayNota_Ex : ArrayList<JTextField>
          - arrayNota_Final : ArrayList<JTextField>
          - arrayNota_Pr : ArrayList<JTextField>
          - no_resul : JLabel
          - resultado_consulta : List<ListadoEvaluacion>
          {static} - serialVersionUID : long
          - x : int
          - y : int
          + PanelResultadoConsultarHistoricoAlumnos()
          + actionPerformed()
          + getArrayAlumno()
          + getArrayConvocatoria()
          + getArrayCurso()
          + getArrayDniAlumno()
          + getArrayNMatAlumno()
          + getArrayNota_Ex()
          + getArrayNota_Final()
          + getArrayNota_Pr()
          + mostrarResultados()
          + resetear()
          - aniadir()
          - aumentarTamanio()
          - cargarElementos()
          - modificarBoton()
      }
    }
  }
  

  capaInterfaz.MenuHistoricoAlumnos.PanelMenuConsultarHistoricoAlumnos .up.|> java.awt.event.ActionListener
  capaInterfaz.MenuHistoricoAlumnos.PanelMenuConsultarHistoricoAlumnos -up-|> javax.swing.JPanel
  capaInterfaz.MenuHistoricoAlumnos.PanelMenuHistoricoAlumnos .up.|> java.awt.event.ActionListener
  capaInterfaz.MenuHistoricoAlumnos.PanelMenuHistoricoAlumnos -up-|> javax.swing.JPanel
  capaInterfaz.MenuHistoricoAlumnos.PanelResultadoConsultarHistoricoAlumnos .up.|> java.awt.event.ActionListener
  capaInterfaz.MenuHistoricoAlumnos.PanelResultadoConsultarHistoricoAlumnos -up-|> javax.swing.JPanel
  capaInterfaz.MenuHistoricoAlumnos.PanelResultadoConsultarHistoricoAlumnos o-- capaInterfaz.JButtonOp : botonGenerarTxt
  capaInterfaz.MenuHistoricoAlumnos.PanelResultadoConsultarHistoricoAlumnos o-- capaInterfaz.JButtonOp : botonOK


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
