@startuml

title Arquitectura Gestion de Asignaturas\n


  

  namespace capaDatos {

  }

  namespace capaInterfaz {
  }

  

  namespace capaLogicaNegocio {
  }


capaLogicaNegocio -- capaDatos
capaLogicaNegocio -- capaInterfaz

right footer

endfooter

@enduml
